### ISSUE TITLE
YAML Tab spacing

### ISSUE THREAD

**Issue by alexsctdph** [manii1917/Practicum#5]
https://github.com/manii1917/Practicum/blob/b7e12dbc2e635be68bc65cff71ee45d55b5d1cf7/Overview_Internship.Rmd#L7-L13

Howdy, I figured our cleaning up would be a good use of the issues portion of github.  The file you knitted the other day with me on the screen share is somehow different than your main branch.  This document won't knit, it fails at line 1 with:

Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Parser error: while parsing a block mapping at line 1, column 1 did not find expected key at line 6, column 5
  
  lines 7 through 13 need to be tabbed over 1 space, so the top part (the YAML) can tell the parser how to knit this document into an HTML.

**Comment by manii1917** [comment]
Sorry, this happened because I didn't upload the most recent version of the file on the repo. The issue is resolved now.
