### ISSUE TITLE
duplicate chunk name

### ISSUE THREAD

**Issue by alexsctdph** [manii1917/Practicum#6]
https://github.com/manii1917/Practicum/blob/b7e12dbc2e635be68bc65cff71ee45d55b5d1cf7/Overview_Internship.Rmd#L286-L320

These two chunks have identical names which the parser does not like when knitting.  It throws the following error:

processing file: Overview_Internship.Rmd
Error in parse_block(g[-1], g[1], params.src, markdown_mode) : 
  Duplicate chunk label 'prettyitup', which has been used for the chunk:

**Comment by manii1917** [comment]
Sorry, this happened because I didn't upload the most recent version of the file on the repo. The issue is resolved now.
