### ISSUE TITLE
Update Objective

### ISSUE THREAD

**Issue by alexsctdph** [manii1917/Practicum#8]
The Data Product is still relevant, but the webpage for CT DPH is not.

https://github.com/manii1917/Practicum/blob/b7e12dbc2e635be68bc65cff71ee45d55b5d1cf7/Overview_Internship.Rmd#L48-L50

(FYI I'm jsut adding a ton of issues to keep track of our work, they're not necessarily all on you to figure out.... having said that, I would love to see the objective stated in your own words as sort of a litmus test for me)

**Comment by manii1917** [comment]
Done.
